---
id: wicked
name: Wicked
full: Wiki application
description: Wicked is a wiki application for Horde.
list: horde
type: application
homepage: https://www.horde.org/apps/wicked
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0
  api: 3.0.0
state:
  release: beta
  api: beta
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^7
    composer:
      horde/horde: ^6
      horde/auth: ^3
      horde/autoloader: ^3
      horde/core: ^3
      horde/db: ^3
      horde/exception: ^3
      horde/form: ^3
      horde/http: ^3
      horde/lock: ^3
      horde/mail: ^3
      horde/mime: ^3
      horde/mime_viewer: ^3
      horde/notification: ^3
      horde/perms: ^3
      horde/prefs: ^3
      horde/rpc: ^3
      horde/text_diff: ^3
      horde/url: ^3
      horde/util: ^3
      horde/vfs: ^3
    ext:
      gettext: '*'
  optional:
    composer:
      pear/text_figlet: '*'
      horde/test: '*'
