<?php

// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/wicked/routes.local.php and run composer horde:reconfigure

use Horde\Wicked\Controller\AdminAttachmentsController;
use Horde\Wicked\Controller\DiffController;
use Horde\Wicked\Controller\HistoryController;
use Horde\Wicked\Controller\OpenSearchController;
use Horde\Wicked\Controller\PageController;
use Horde\Wicked\Controller\PreviewController;

// Specific routes must come before the catch-all
$mapper->buildRoute(uri: '/history', name: 'History')
    ->withController(HistoryController::class)
    ->withSecondaryRoute('/history.php')
    ->add();

$mapper->buildRoute(uri: '/diff', name: 'Diff')
    ->withController(DiffController::class)
    ->withSecondaryRoute('/diff.php')
    ->add();

$mapper->buildRoute(uri: '/preview', name: 'Preview')
    ->withController(PreviewController::class)
    ->withSecondaryRoute('/preview.php')
    ->add();

$mapper->buildRoute(uri: '/admin/attachments', name: 'AdminAttachments')
    ->withController(AdminAttachmentsController::class)
    ->withSecondaryRoute('/admin/attachments.php')
    ->add();

$mapper->buildRoute(uri: '/opensearch', name: 'OpenSearch')
    ->withController(OpenSearchController::class)
    ->withSecondaryRoute('/opensearch.php')
    ->add();

// Catch-all route for wiki pages — maps any path under the wicked webroot
// to the page parameter, replacing the legacy .htaccess RewriteRule.
// The secondary route handles legacy display.php?page=X URLs.
$mapper->buildRoute(uri: '/*page', name: 'Pages')
    ->withController(PageController::class)
    ->withDefaults(['page' => 'Wiki/Home'])
    ->withSecondaryRoute('/display.php')
    ->add();
