<?php
// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/wicked/routes.local.php and run composer horde:reconfigure

use Horde\Wicked\Controller\DiffController;
use Horde\Wicked\Controller\HistoryController;
use Horde\Wicked\Controller\PageController;
use Horde\Wicked\Controller\PreviewController;

// Specific routes must come before the catch-all
$mapper->buildRoute(uri: '/history', name: 'History')
    ->withController(HistoryController::class)
    ->add();

$mapper->buildRoute(uri: '/diff', name: 'Diff')
    ->withController(DiffController::class)
    ->add();

$mapper->buildRoute(uri: '/preview', name: 'Preview')
    ->withController(PreviewController::class)
    ->add();

// Catch-all route for wiki pages — maps any path under the wicked webroot
// to the page parameter, replacing the legacy .htaccess RewriteRule.
$mapper->buildRoute(uri: '/*page', name: 'Pages')
    ->withController(PageController::class)
    ->withDefaults(['page' => 'Wiki/Home'])
    ->add();
