<?php
// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/wicked/routes.local.php and run composer horde:reconfigure

use Horde\Wicked\Controller\PageController;

// Catch-all route for wiki pages — maps any path under the wicked webroot
// to the page parameter, replacing the legacy .htaccess RewriteRule.
$mapper->buildRoute(uri: '/*page', name: 'Pages')
    ->withController(PageController::class)
    ->withDefaults(['page' => 'Wiki/Home'])
    ->add();
